services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bss-parking-app
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=db_bss_parking
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel_password
    volumes:
      - app_storage:/var/www/html/storage/app
      - app_logs:/var/www/html/storage/logs
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - parking-network

  mysql:
    image: mysql:8.0
    container_name: bss-parking-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_bss_parking
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_bss_parking.sql:/docker-entrypoint-initdb.d/db_bss_parking.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - parking-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bss-parking-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - parking-network

volumes:
  mysql_data:
  app_storage:
  app_logs:

networks:
  parking-network:
    driver: bridge 