services:
  mysql:
    image: mysql:8.0
    container_name: bss-parking-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_secure_password}
      MYSQL_DATABASE: ${DB_DATABASE:-db_bss_parking}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-laravel_secure_password}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_bss_parking.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    command: >
      --default-authentication-plugin=mysql_native_password
      --innodb-buffer-pool-size=256M
      --max_connections=100
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-root_secure_password}"]
      timeout: 10s
      retries: 5
      interval: 10s
      start_period: 30s
    restart: unless-stopped
    networks:
      - parking-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bss-parking-app
    ports:
      - "${APP_PORT:-80}:80"
    environment:
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=${APP_DEBUG:-false}
      - APP_URL=${APP_URL:-http://localhost}
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-db_bss_parking}
      - DB_USERNAME=${DB_USERNAME:-laravel}
      - DB_PASSWORD=${DB_PASSWORD:-laravel_secure_password}
    volumes:
      - app_storage:/var/www/html/storage/app
      - app_logs:/var/www/html/storage/logs
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - parking-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      timeout: 10s
      retries: 3
      interval: 30s
      start_period: 60s

volumes:
  mysql_data:
    driver: local
  app_storage:
    driver: local
  app_logs:
    driver: local

networks:
  parking-network:
    driver: bridge 